document.write(typeof "using the typeof operator before this string to say what data type this sentence is");
document.write("<br>");
document.write(true + " 50" + 5);
document.write("<br>");
document.write(2E310);
document.write("<br>");
document.write(-2E310);
document.write("<br>");
document.write(8 > 6);
document.write("<br>");
document.write(8 < 6);
console.log(2 + 2);
console.log(2 > 5);
document.write('<br>');
document.write(55 == 100);
document.write('<br>');
document.write(5 == 5);